#if 1
#include "arbitrary_ntt.hpp"
#include "binpow.hpp"
#include "debug.hpp"
#include "io.hpp"
#include "lca.hpp"
#include "mod.hpp"
#include "nd_vector.hpp"
#include "poly.hpp"
#include "poly_gen.hpp"
#include "poly_gen_dyn.hpp"
#include "poly_interpolate.hpp"
#include "rmq.hpp"
#include "rolling_hash.hpp"
#include "segment_tree.hpp"
#include "smawk.hpp"
#include "universal_euclidean.hpp"
#include "y_combinator.hpp"
#include "zip_with.hpp"
#else
#endif
