#include "binpow.hpp"
#include "debug.hpp"
#include "fast_io.hpp"
#include "mod.hpp"
#include "nd_vector.hpp"
#include "poly.hpp"
#include "polynomial_interpolation.hpp"
#include "rmq.hpp"
#include "segment_tree.hpp"
#include "universal_euclidean.hpp"
#include "y_combinator.hpp"

